{
 "title": "Trail Sampling",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Policy Match %",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_traces_total{decision=\"matched\"}[$__rate_interval])) by (policy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace Outcome",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_traces_total{decision=\"dropped\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(rate(trail_sampling_policy_traces_total{decision=\"sampled\"}[$__rate_interval]))",
     "legendFormat": "Kept"
    }
   ]
  },
  {
   "title": "Traces/s Kept",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_traces_total{decision=\"sampled\"}[$__rate_interval])) by (policy)",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  {
   "title": "Traces/s Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_traces_total{decision=\"dropped\"}[$__rate_interval])) by (policy)",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  { "title": "Spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Policy Match %",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_spans_total{decision=\"matched\"}[$__rate_interval])) by (policy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Span Outcome",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_spans_total{decision=\"dropped\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(rate(trail_sampling_policy_spans_total{decision=\"sampled\"}[$__rate_interval]))",
     "legendFormat": "Kept"
    }
   ]
  },
  {
   "title": "Spans/s Kept",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_spans_total{decision=\"sampled\"}[$__rate_interval])) by (policy)",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  {
   "title": "Spans/s Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(trail_sampling_policy_spans_total{decision=\"dropped\"}[$__rate_interval])) by (policy)",
     "legendFormat": "{{policy}}"
    }
   ]
  }
 ]
}